### PR TITLE
Ws/hooks

### PR DESCRIPTION
**Pull request by leboem**

### CODE REVIEW

**Comment by kyaso** [comment]
Maybe we should add another tag for changes to website backend, such as hooks, actions.

**Comment by leboem** [comment]
> Maybe we should add another tag for changes to website backend, such as hooks, actions.

Do you have any ideas? WB = Website Backend, WF = Website Frontend?

**Comment by kyaso** [comment]
Sounds good.

**Comment by leboem** [comment]
I will change it! wait a sec

**Review by kyaso — APPROVED** [review]
LGTM

**Pull request merged**
